apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-express
  labels:
    app: simple-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-express
  template:
    metadata:
      labels:
        app: simple-express
    spec:
      containers:
      - name: simple-express
        image: madeofhuman/simple-express
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
